services:
  - type: web
    name: laravel
    env: php
    region: oregon
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: php artisan serve --host 0.0.0.0 --port 3000
    autoDeploy: true
